### ISSUE TITLE
Define next iteration of sync

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1844]
Currently we have a minimal viable sync algorithm. Need to establish what work is required to improve sync performance and reliability. e.g distribute requests across peers, more coordination between block propagation manager and sync strategy.

### TODO

* [x] Start from common ancestor instead of finalised epoch
* [ ] Avoid selecting the same peer for subsequent batches if possible
* [x] Apply reputation penalties to peers
* [ ] Implement a smarter/more efficient approach to verifying contested batches
* [ ] Request updated status from all peers when a sync finishes
* [ ] More intelligent grouping of target chains in non-finalised period
* [ ] Consider starting background sync of less popular chains after reaching head

**Comment by ajsutton** [comment]
Remaining issue: when sync switches to a new chain it optimistically assumes the new chain extends the old one until it finds the blocks don't match.  That means it will keep downloading the currently queued batches from the old chain.  When the old chain has no remaining peers, those batches can never be downloaded and the sync gets stuck.   Need to change it so that when a batch from an old chain has no available peers, it is replaced with a batch from the new chain (for the same range).
