### ISSUE TITLE
Enable running validator client service in separate process

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1918]
The basic architecture is now in place, but there's a few things to do to make this ready for real world deployment:

* [x] Switch to standard REST API
  * [x] Implement head update event (published whenever beacon chain advances it's head - either on a new head block importing or after running fork choice 1/3rd through a slot, effectively selecting the skipped slot)
  * [x] Handle clients that are slow to read from events stream to ensure we continue to publish to faster clients quickly and don't build up a huge number of pending events in memory
  * [x] Allow attestation and production duties, plus block creation and publishing to be performed one slot in advance (ie when the block for the last slot of epoch 1 is selected, we can calculate block production for epoch 2 and attestation duties for epoch 2 & 3 even if the start time of the first slot for epoch 2 hasn't been reached)
  * [x] Implement the remaining REST APIs from the validator required set (separate tickets for those - they map pretty closely to our existing APIs)
 * [x] Create/find java client to read event streams
 * [x] Switch validator client to be driven off of it's own clock and the head events
 * [x] Reset scheduled duties when the event stream is disconnected (we might have missed a reorg event while reconnecting)
 * [x] Review CLI options and prepare them to be fully supported APIs (particularly adapting to not needing to explicitly enable remote validator APIs)
    * [x] Support loading options from a config file
 * [ ] Don't run in-process validator service if there are no validators specified
 * [x] Complete separation of validator duties to attestation and block production duties.
 * [x] Default to different log file for validator client
 * [x] Move slashing protection directory out of data path

**Comment by MadelineMurray** [comment]
@ajsutton - moving this epic over to you in case you still want/need it.  Otherwise, close away :-)

**Comment by ajsutton** [comment]
Calling this one done.  External validator now works well and is using only standard REST APIs.
