### ISSUE TITLE
v0.12.1 - Networking updates

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2035]
### Description
Implement any networking changes in v0.12.1 beyond Gossipsub 1.1.

TODO & Related Issues:
- [ ] https://github.com/PegaSysEng/teku/issues/2077 - Enforce type-specific size limits for rpc chunks
- [ ] https://github.com/PegaSysEng/teku/issues/2078 - Limit response sizes & and make error message a sequence of bytes
- [x] https://github.com/PegaSysEng/teku/issues/2079 - Loosen aggregation propagation restrictions
- [x] https://github.com/PegaSysEng/teku/issues/2080 - Implement missing validation
- [x] https://github.com/PegaSysEng/teku/issues/2081 - Use Gossipsub v1.1 API
- [x] https://github.com/PegaSysEng/teku/issues/2082 - Change SingleAttestationTopicHandler Topic Name
