### ISSUE TITLE
Implement weak subjectivity checkpoints

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2273]
### Description
As a node operator, I want to be able to use weak subjectivity checkpoints so that I can resync securely. 

See this write-ups for the current thinking on this: 
* https://notes.ethereum.org/@adiasg/weak-subjectvity-eth2
* https://github.com/ethereum/eth2.0-specs/blob/7a46181853a34d74e8c3da08ad23686c0918f961/specs/phase0/weak-subjectivity.md

Absorbing #1950 here: if Teku does not have access to a known good state (such as a checkpoint, or a self-calculated state) within the WSP it should warn the operator and (probably) refuse to start.

We should/could also define a mechanism for providing checkpoints state snapshots to users wishing to sync.

### TODOS

- [x] Accept a weak subjectivity checkpoint (WSC) CLI argument
  - This is in flux, but one suggested interim format is: `blockRoot:epochNumber`
- [x] Handle case where latest finalized block is outside of the weak subjectivity period (WSP) and no in-range WSC is supplied 
- [x] Handle case where local chain is inconsistent with the supplied WSC
- [x] Handle case where sync falls out of the WSP
- [x] Prevent any block inconsistent with configured WSC from being imported
- [x] If WSC is configured, validate that peers agree with this checkpoint
- [x] Add some method for clearing stored WS configuration
- [x] Add some method for running the client if we hit a period of non-finalization longer than the WSP
- [x] Clean up logging - make sure appropriate logs are going to console at a reasonable rate
- [x] Disconnect peers that send a block inconsistent with the ws checkpoint
- [x] Rework checks against WSP while the client is running as necessary based on discussion in WS working group channel
- [x] Fully enable WS features (make CLI args visible, use strict error handling)

Out of scope:
- Rework sync algorithm to work with WSC.  See: #1844 
- Starting up from an actual WS state.  See: #3063

**Comment by mbaxter** [comment]
We should probably also have checks that cause teku to shut down if sync falls behind the weak subjectivity period.

**Comment by benjaminion** [comment]
Transposing comments from Telegram "Eth2 Weak Subjectivity WG" to here:

> Feature Request:
>
> (1) Take WSS as a CLI parameter input
> (2a) IF the WSS height is > local last finalized height, then ASSERT during block sync that WSS is in the path at the appropriate height. Emit descriptive critical error if this assert fails, then exit client process.
> (2b) IF WSS height <= local last finalized height, then ASSERT that the local state at the WSS height is the same as the WSS input. Emit descriptive critical error if this assert fails, then exit client process.
>
> I'm assuming here that clients start block sync from their last finalized block. If your client starts its sync from elsewhere, you'll have to change the logic 2a & 2b so that it maintains the same functionality for your sync strategy. Happy to discuss this if needed.
