### ISSUE TITLE
Update BeaconState to 0.1 spec

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#235]
There have been a bunch of changes to BeaconState that it would be worth incorporating before tackling #233.

To meet the 0.1 spec, we need the following changes to the BeaconState variables.

- [x] `fork-data` -> `fork` rename (done in #238)
- [x] `validator_registry_latest_change_slot` -> `validator_registry_update_epoch` rename (to be done as part of #236)
- [x] remove `validator_registry_exit_count` (done in #247)
- [x] remove `validator_registry_delta_chain_tip` (to be done in #248)
- [x] remove `latest_vdf_outputs` (done in #237)
- [x] remove `shard_committees_at_slots` (to be done in #241; partially done in #256)
- [x] remove `persistent_committees`, `persistent_committee_reassignments` (done in #240)
- [x] add `previous_epoch_start_shard`, `current_epoch_start_shard`, `previous_calculation_epoch`, `current_calculation_epoch`, `previous_epoch_seed`, `current_epoch_seed` (done in #256)
- [x] rename `previous_justified_slot`, `justified_slot`, `finalized_slot` to `_epoch`  (to be done as part of #236)
- [x] add `latest_index_roots` (to be done in #248)
- [x] rename `latest_penalized_exit_balances` to `latest_penalized_balances` (done in #239)
- [x] rename `processed_pow_receipt_root` to `latest_eth1_data` and make class `Eth1Data` (done in #242)
- [x] rename `candidate_pow_receipt_roots` to `eth1_data_votes` and make class `Eth1DataVote` (done in #242)
