### ISSUE TITLE
Support forks

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3356]
### Description
Refactor teku so that spec logic is versionable.  See prototype for direction: https://github.com/ConsenSys/teku/pull/3546

Tasks:
- [x] Investigate how to version datastructures (#3504)
- [ ] Migrate from static constants to instance-based constants (#3394)
- [ ] Migrate container definitions and datastructures into `spec` (#3564)
- [ ] Migrate all spec-related logic into `spec` package (#3596)
- [ ] Address any pending todos (search: `TODO(#3356)`)

**Comment by rolfyone** [comment]
https://hackmd.io/@HWeNw8hNRimMm2m2GH56Cw/HkTzLKOov
