### ISSUE TITLE
The Merge

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4226]
Implement THE MERGE.

### Instructions

For instructions on how to run interop see:
- #4438 
- #4431
- #4428 
- #4424 

### TODO

TODO list for interop:

 * [x] #4350 Enable CI on merge branch
 * [x] #4351 Rebase merge implementation onto Altair fork
 * [x] #4361 Implement `SszUnion`
 * [x] (#4362, ?) Update to the latest merge core spec
 * [x] #4368 Sort out reference test failures 
 * [x] #4345
 * [x] #4346 Update to interop Engine API
 * [x] #4417
 * [x] #4423 
 * [x] #4424
 * [x] #4428 
 * [x] #4429 
 * [x] #4431
 * [x] #4438
 * [x] #4445
 * [x] #4458
 * [x] Implement the right Optimistic sync (see #4458)
 * [x] #4348 Support Async payload execution
 * [x] #4349 Sync process
 * [x] #4357 Publish docker image of merge branch
