### ISSUE TITLE
Kintsugi 🍵

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4504]
### Description
Tracks the Merge Kintsugi implementation (November sprint): ref. reference: https://hackmd.io/@n0ble/kintsugi-spec

- productize and move `merge-interop` branch to `master`

  - [x] add merge spec datastructures #4503 
  - [x] extend `TestSpecFactory` #4527
  - [x] remove blind altair empty syncAggregate creation on block creation. (reference: https://github.com/ConsenSys/teku/pull/4503#discussion_r735744787) #4528
  - [x] add Merge in `api.schema.merge` #4537
  - [x] introduce a new way of running an entire set of UT against multiple Milestone #4563
  - [x] introduce Merge in `teku.spec.logic` package
    -  switch `SpecVersion::createMerge` to real Merge
  - [ ] expand IT by implementing `GetBlockV2IntegrationTest::shouldGetMergeBlock`
  - [x] #4593
  - [x] implement merge specific reference test support (#4597)
  - [x] #4641
  - [x] #4659
  - [x] #4668

- implements specs 1.1.5 changes:

  - [x] Add terminal block hash override ethereum/consensus-specs#2617
  - [x] #4226 
  - [x] #4670
  - [x] Remove Union from ExecutionPayload transaction type ethereum/consensus-specs#2684
  - [x] #4666
  - [x] Add payload id as a return value to notify_forkchoice_updated ethereum/consensus-specs#2711
  - [x] update penalty params for Merge ethereum/consensus-specs#2698

 - [ ] #4599  implement new [optimistic sync](https://hackmd.io/@n0ble/kintsugi-spec#Optimistic-sync) (additional ref: https://hackmd.io/Ic7VpkY3SkKGgYLg2p9pMg?view) #4599 
- [x] #4716 

nice to have:
- [ ] submit a PR to [tuweni](https://github.com/apache/incubator-tuweni) to implement `Bytes4`, `Bytes8` and `Bytes20`
- [x] #4667 introduce Merge state generator in `MockStartBeaconStateGenerator::createInitialBeaconState` by adding `ExecutionPayloadHeader` (note we've already done enough here to pass all reference tests)

far in the future:

- [ ] remove default values and enforce validation in transition params (`SpecConfigBuilder::MergeBuilder::validate()`)
- [ ] remove --X prefix and publish new params in documentation
  - "--Xee-endpoints", "--Xee-endpoint" 
  - "--Xvalidators-fee-recipient-address"

**Comment by ajsutton** [comment]
Created separate tickets for the remaining parts of this (except adding the new Bytes types to tuweni, not sure if that's worth the effort or whether it makes sense for Tuweni to support every length of bytes as a special type).  So going to close this as we're up and running on Kintsugi fine now.
