### ISSUE TITLE
[Merge] Kiln Meta-Issue 🔥🧱

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4972]
### Description
Tracking issue for work required to fully support Kiln meta-spec (https://hackmd.io/@n0ble/kiln-spec)

*M0* (Implementation started):
 * [x] Create tracking issue (this one!)

*M1* (Kiln v1 Spec implemented):
 * [x] Support [Consensus spec v1.1.9](https://github.com/ethereum/consensus-specs/tree/v1.1.9/specs/bellatrix)
 * [x] Pass Consensus spec v1.1.9 reference tests
 * [x] Rename "Merge" -> "Bellatrix" 
 * [x] Rename `execute_payload` to `notify_new_payload`
 * [x] Rename `receipt_root` -> `receipts_root`
 * ~[ ] Run against `mergemock`~ - merge mock doesn't support the `eth` namespace as required by Engine API so merge block can't be created.
 * [x] #5057

*M2* (Kiln v2 Spec implemented):
 * [x] #4958 Support authentication for engine API
 * [x] #4956 Use engine_exchangeTransitionConfigurationV1 to check EL config
 * [x] #5045

*M3* (Many-toMany Interop):
 * [x] Run many:many devnet with transition (`TTD` occurring 8+ epochs in the beacon chain)
 * [x] Send EL Txs that transfer ETH and deploy a contract which are successfully executed on chian

*M4* (Weekly devnet):
 * [x] Participate in EF led weekly devnet
 * [x] Be on the devnet during the merge transition process and process EL TXs
 * [x] Sync from genesis using Optimistic Sync

*M5* (All-to-All persistent testnet):
 * [ ] Kiln specification considered feature complete for mainnet Merge
 * [x] Run many:many devnet with transition
 * [x] Run stable on devnet
 * [x] Create README for the public to connect (https://besu.hyperledger.org/en/latest/Tutorials/Merge-Testnet/)

*M6* (Kiln code released)
 * [x] Mainnet-compatibile sync support
 * [x] Merge Kiln code into main branch
 * [x] Add `--network kiln` CLI flag
 * [x] Add basic documentation for public to connect to Kiln
 * [x] Stable release with Kiln support

**Comment by ajsutton** [comment]
Closing this as all the work is done on the teku side now.  Making sure the kiln specification is feature complete for MainNet is a specs repo concern.
