### ISSUE TITLE
Path to Jamboree

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#584]
### Description
List of tasks needed to complete to make it to the Jamboree:
## Critical Path
- [x] Finish spec update: v0.5.1 #637 (@cemozerr )
- [x] Finish spec update: v0.7.1  (@cemozerr @dangerousfood @schroedingerscode )
- [x] Finality issues with networked nodes (@jrhea and/or @cemozerr )
- [x] Validator Client (@cemozerr)
- [x] More robust clock sync. Right now we have a timer, that will delay the next slot (locally) if processing takes too long. (@jrhea)
  - [x] Clock always starts from `GENESIS_SLOT`
  - [x] Modular way to swap out how slot events are triggered
 BC's ability to finalize.  Sweep values with different methods and share the results.
- [x] ETH1 node to kick off ETH2 genesis event (@dangerousfood )
  - [x] Develop a way to kick off genesis event quickly (without waiting forever for the event to fire)
- [x] Implement reference state transition tests #465  (@schroedingerscode )
- [x] Profile and Improve Epoch Processing Efficiency #697
