### ISSUE TITLE
Add Capella Helpers functions

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#6320]
Reference: https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#helpers

- [x] has_eth1_withdrawal_credential
- [x] is_fully_withdrawable_validator
- [x] is_partially_withdrawable_validator

Note: `withdraw_balance` will be done separately (TODO - link issue)
