### ISSUE TITLE
Update to spec v5.1 

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#637]
### Description
Tasks related to spec upgrade v5.1:

- [x] On Genesis Updates (Part of Spec PR #711): #545 
- [x] Use signed_root For Block ID Purposes in Blocks/State - (Spec PR #816): #518 
- [x] Employ consistent style for function naming: #500 
- [x] Minor formatting/typos/etc #494 
- [x] Update Eth2Genesis Event - (Deposit_Contract PR #22): #493 
- [x] Update Eth2 Deposit Event - (Deposit_Contract PR #21): #492 
- [x] Minor refactor to process_slashings to reduce repeated computation (Spec PR #714): #490 
- [x] Make 'Any active validator' statements stricter (Spec PR #703): #489 
- [x] Do not check withdrawal credentials for existing validators (Spec PR #750): #487 
- [x] Cache justified/finalized roots in state for use in state transition (Spec PR #756): #483
- [x] Only attempt to reward proposer if attestation exists for validator index (Spec PR #744): #481 
- [x] Handle get_base_reward when no previous balance (Spec PR #718): #480
- [x] Handle when no attestations available for crosslinking (Spec PR #717): #479 
- [x] Fix committee assignment bugs (Spec PR #699): #478 
- [x] Fix latest_randao_mixes initialization value (Spec PR #713): #477
- [x] Add HistoricalBatch tuple, remove merkle_root in favor of hash_tree_root functions. - (Spec PR #739): #476 
- [x] Fix the "ready to exit" condition in `update_validator_registry` (Spec PR #705): #475 
- [x] Fix up previous epoch logic around genesis (Spec PR #672): #474 
- [x] Epoch Transition at Start of Epoch - (Spec PR #732, #741): #473
- [x] Favor Higher Hash Tree Root for Ties in LMD GHOST - (Spec PR #737): #472 
- [x] Clarify basic/non-basic SSZ types - (Spec PR #724): #471 
- [x] Add tuple lengths to eliminate length mixin for some BeaconState, Deposit fields - (Spec PR #723): #470 
- [x] SSZ Spec Changes - (Spec PR #696): #469 
- [x] Remove signature/proof_of_possession from message_hash calculation. - (Spec PR #725): #468 
- [x] Bugfixes (in progress by @cemozerr, @schroedingerscode, @akhila-raju)
- [x] Merge to master (will be started after bugfixes completed)

**Comment by akhila-raju** [comment]
Did a run-through of all of the checked tasks and implemented those that were missing. The tasks that still need to be looked at are mostly the ones related to SSZ and Eth2Genesis/Deposit events.

**Comment by akhila-raju** [comment]
Did one more pass-through; all that's missing is 3 SSZ-related tasks that @schroedingerscode will look over, 2 deposit contract tasks I will work on, bug fixes which @cemozerr, @schroedingerscode, and I are working on, and then we have merge to master!

**Comment by jrhea** [comment]
resolved by #687
