### ISSUE TITLE
Define new constants

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6377]
New constants to be defined in `tech.pegasys.teku.spec.config.Constants`
- [beacon constants](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#constants)
  - [ ] `BLOB_TX_TYPE`
  - [ ] `VERSIONED_HASH_VERSION_KZG`
  - ~~`DOMAIN_BLOBS_SIDECAR`~~ 
- [p2p](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/p2p-interface.md#configuration)
  - [ ] `MAX_REQUEST_BLOBS_SIDECARS`
  - [ ] `MIN_EPOCHS_FOR_BLOBS_SIDECARS_REQUESTS`
