### ISSUE TITLE
Define new types

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6378]
There are several new types defined in the spc. When these types are just alias of a generic type we use the generic one. But if these types are more complex or requires specific validation we have to create a specific class.

from [polynomial commitments types](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/polynomial-commitments.md#custom-types) we need to define:

- [ ] `KZGCommitment`  we need an ssz version of it like SszPublicKey (will be in `BeaconBlockBody` schema to build a list of them via `SszListSchema.create(KZGCommitment, ...)`)
- [ ] `KZGProof` we need an ssz version of it like SszPublicKey (will be part of `BlobsSidecar` schema)
- [ ] `Blob` we need an ssz version defined via SszByteVectorSchema.create() (will be part of `BlobsSidecar` schema as `SszListSchema.create(Blob, ..)`)
