### ISSUE TITLE
Define new presets

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6379]
### new presets:
- [ ] [mainnet](https://github.com/ethereum/consensus-specs/blob/dev/presets/mainnet/eip4844.yaml) 
- [ ] [minimal](https://github.com/ethereum/consensus-specs/blob/dev/presets/minimal/eip4844.yaml) 

new fields:
-`FIELD_ELEMENTS_PER_BLOB`
-`MAX_BLOBS_PER_BLOCK`

### new fork in configurations for [mainnet](https://github.com/ethereum/consensus-specs/blob/dev/configs/mainnet.yaml) and [minimal](https://github.com/ethereum/consensus-specs/blob/dev/configs/minimal.yaml) 
- [ ] `EIP4844_FORK_VERSION`
- [ ] `EIP4844_FORK_EPOCH`
