### ISSUE TITLE
Implement MiscHelpersEip4844

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6391]
https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#misc

implement this helper functions. The functions will require usage of the kzg library
- [ ] process_blob_kzg_commitments
- [ ] validate_blobs_sidecar
- [ ] is_data_available
  - [ ] ~~retrieve_blobs_sidecar will be represented by a `SafeFuture<BlobsSidecar>`~~ Currently the plan is not implementing an async\optimistic blob retrival. So blobs will be provided immediately if there.
- [ ] kzg_commitment_to_versioned_hash
- [ ] tx_peek_blob_versioned_hashes
- [ ] verify_kzg_commitments_against_transactions
