### ISSUE TITLE
Rename EIP4844 Milestone to Deneb

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#6608]
https://github.com/ethereum/beacon-APIs/pull/289

**Comment by zilm13** [comment]
Made in #6783 with several TODOs which should be completed when rename in spec is done

**Comment by zilm13** [comment]
Final cleanup TODOs:
- [x] Update spec link to deneb in https://github.com/ConsenSys/teku/blob/a764ee42742b950fe66ca87b5f1e787b5e45e977/beacon/sync/src/main/java/tech/pegasys/teku/beacon/sync/fetch/FetchBlockAndBlobsSidecarTask.java#L49-L51
- [x] Update spec link to deneb, remove p https://github.com/ConsenSys/teku/blob/a764ee42742b950fe66ca87b5f1e787b5e45e977/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/BlobsSidecarsByRangeMessageHandler.java#L134-L137
- [x] Make DENEB constant == "deneb" when reference tests are updated https://github.com/ConsenSys/teku/blob/a764ee42742b950fe66ca87b5f1e787b5e45e977/eth-tests/src/main/java/tech/pegasys/teku/ethtests/TestFork.java#L21-L22
- [x] Clean up hack when reference tests are updated https://github.com/ConsenSys/teku/blob/a4a0bd7c88f8f9799031fe6bb5c4e559bd66f9ab/eth-reference-tests/src/referenceTest/java/tech/pegasys/teku/reference/altair/fork/TransitionTestExecutor.java#L50-L53
- [x] Clean up hack when reference tests are updated https://github.com/ConsenSys/teku/blob/a4a0bd7c88f8f9799031fe6bb5c4e559bd66f9ab/eth-reference-tests/src/referenceTest/java/tech/pegasys/teku/reference/altair/fork/ForkUpgradeTestExecutor.java#L41-L44
- [x] Update setters and override when configs are updated https://github.com/ConsenSys/teku/blob/a764ee42742b950fe66ca87b5f1e787b5e45e977/ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/builder/DenebBuilder.java#L28
- [x] Update `EIP4844_FORK_VERSION` and `EIP4844_FORK_EPOCH` names in all configs: https://github.com/ConsenSys/teku/tree/a764ee42742b950fe66ca87b5f1e787b5e45e977/ethereum/spec/src/main/resources/tech/pegasys/teku/spec/config/configs and https://github.com/ConsenSys/teku/tree/a764ee42742b950fe66ca87b5f1e787b5e45e977/ethereum/spec/src/test/resources/tech/pegasys/teku/spec/config/standard
- [x] Avoid exposing `4844` out of ckzg wrapper

**Comment by StefanBratanov** [comment]
We can close this finally with https://github.com/ConsenSys/teku/pull/6842 merged
