### ISSUE TITLE
Artemis Simulation Executive (ASE)

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#663]
### Description
An artemis simulation executive (ASE) is needed for research, development and testing of the beacon chain.  ASE will enable us to script batch runs with any number of parameter sweeps.  It should read these parameters from a new config file that specify (for each run) things like: node topology, number of nodes, constants, output variables, etc.

## Basic Functionality

The executive could work like this:
1) read from simulation executive configuration file that specifies the number of runs and what params should be changed on each iteration.
2) modify the artemis config.toml files for each node with the parameters needed for an individual run
3) execute the run.sh script with the new config.toml file and a unique output file
4) repeat steps 2 & 3 until all scripted runs are complete.

Prerequisites for ASE:

- [x] Create run script #615 
- [x] run script mod for custom config.toml and output.json/csv #662 
- [x] Need existing output configs moved to toml file #636 
- [x] Dynamic JSON & CSV output fields #638 
- [x] Configurator script #664

## Future Enhancements

- Add outer loop execution to allow for black box optimization
- Visualization of runs (plots, heatmaps, confusion matrices, etc)
- Automated Root Cause Analysis (RCA)
- Output aggregation and classification for use in ML algorithms
