### ISSUE TITLE
Implement Blob Decoupling

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#6822]
[EIP-4844: Free the blobs #3244](https://github.com/ethereum/consensus-specs/pull/3244)

#### SSZ Containers
- [x] #6776 

#### KZG
- [x] #6782 

#### Gossip
- [x] #6777 

#### RPC
- [x] #6778 
- [x] #6821 
- [x] #6830 
- [x] #6834
- [x] #6870 
- [x] #7246

#### Block Import and State Transition
- [x] #6848
- [x] #6849
- [x] #7080
- [x] #7110
- [x] #7112

#### Validator Coordinator
- [x] Revisit block production

#### Sync
- [x] #6948 
- [x] #6985 
- [x] #7010 
- [x] #7243
- [x] #7244

#### Engine API
- [x] https://github.com/ethereum/execution-apis/pull/402

#### Builder API
- [x] #7170
	
#### Storage
- [x] #6837
- [x] #7111
	
#### Beacon API
- [x] #6781 
- [x] #6819
- [x] #7012
- [x] #7013
- [x] #7019
- [x] #7048
- [x] #7075

#### Validator Client
- [x] #6967
- [x] #6959
- [x] #6963
- [x] #6966
- [x] Remote call from VC -> BN for creating/sending `BlockContents`

#### Cleanup
- [x] #6831
- [x] #6832
- [x] #6833
- [x] Remove old way of historical and recent block sync with coupled blobs
- [x] Remove old way of forward sync with coupled blobs
- [x] Remove `TODO: remove when blobs decoupling sync is implemented` and `TODO: remove once the block publishing is switched to a decoupling version`

#### Nice to have
- [x] #6880
- [x] #6881

**Comment by StefanBratanov** [comment]
Finally closing this since all tasks are done :)
