### ISSUE TITLE
Implement validator aggregator selection changes for DVT

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#6851]
[Link to detailed description](https://docs.google.com/document/d/1q9jOTPcYQa-3L8luRvQJ-M0eegtba4Nmon3dpO79TMk/edit?usp=sharing)

In short, when configured as part of a DVT (distributed validator technology) cluster, validators are unable to work out directly whether they are to perform attestation (or sync committee) aggregation duty for a committee. This is because they do not have access to the entire signing key needed to generate the signature used for aggregator selection.

To support this, some changes to the validator client are needed. At high-level (see [the doc](https://docs.google.com/document/d/1q9jOTPcYQa-3L8luRvQJ-M0eegtba4Nmon3dpO79TMk/edit?usp=sharing) for details),

1. Configure the validator client to know that it is part of a DVT cluster. I have a slight preference for the manual method (`--distributed` flag on the VC) rather than automatic detection, but happy to discuss.
2. If distributed mode is active, then modify the control flow after attesting in order to consult the beacon node about whether the validator is an aggregator or not, after supplying a partial signature. Also modify the control flow for sync committee aggregation duty.

These changes use new standard beacon APIs and should be generic across DVT solutions. (This is why I prefer manual configuration via a flag - automatic detection might be solution-specific or fragile.)

**Tasks**
- [x] Beacon committee endpoint
- [x] Sync committee endpoint
- [ ] Documentation page for SSV and Obol DVT #8252

**Comment by rolfyone** [comment]
It sounds like the latest DVT solution won't be requiring beacon-api changes, so these suggested changes are going to be fairly specific to this implementation - worth taking into consideration while prioritising...
https://github.com/ethereum/distributed-validator-specs
emerging spec...

**Comment by benjaminion** [comment]
That spec is looking quite old right now, and doesn't deal with aggregators at all afaics (which might be a blind-spot). We should get some clarity on what the current state of play is. There are only two major implementers of DVT that I'm aware of at the moment, so anything we implement is inevitably going to be fairly application specific. Would definitely prefer to be adhering to whatever "standard" emerges, though.

**Comment by rolfyone** [comment]
I was talking to @saltiniroberto , they're working on a fork... He's actively working on it though.

**Comment by xenowits** [comment]
> That spec is looking quite old right now, and doesn't deal with aggregators at all afaics (which might be a blind-spot). We should get some clarity on what the current state of play is. There are only two major implementers of DVT that I'm aware of at the moment, so anything we implement is inevitably going to be fairly application specific. Would definitely prefer to be adhering to whatever "standard" emerges, though.

Completely agree with your comment @benjaminion . As a side note, this solution _might_ look like application-specific but is not since it is applicable for **any DVT middleware** solution. Also, other teams like lodestar and nimbus are already implementing this solution and we will probably start testing them from Q2. At Obol, teku is the [most supported client](https://github.com/ObolNetwork/charon#project-status) for as of now and we use teku for almost all of our integration tests. So, it would be great to have these aggregator changes implemented at the earliest so that we can test them out. This would make teku a "fully DVT-compatible" client.

Not sure about the dv-specs since it's outdated and on the other hand, 1000+ obol DV clusters are running [obol's DV middleware client](https://github.com/ObolNetwork/charon) on goerli now alongwith 5 clusters on mainnet.

**Comment by aussiestake** [comment]
Is there any update on this?

**Comment by aussiestake** [comment]
As discussed with @Paul Harris on Discord understanding 1) the spec is not complete, 2) some are testing on mainnet with Obol and 3) it's a small change, please could I request that this is included and put behind a feature toggle.

**Comment by lucassaldanha** [comment]
Currently implementing an MVP of this feature.
