### ISSUE TITLE
Prometheus Metrics

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#712]
### Description
Implement metrics as defined in: 

  https://github.com/ethereum/eth2.0-metrics/blob/master/metrics.md

using Pantheon's kick ass implementation.

Tasks:
- [x] Publish Pantheon's metrics module to bintray (@ajsutton )
- [ ] Implement eth1 processing metrics #708 
- [ ] Implement epoch metrics #707 
- [ ] Slot metric beaconchain_current_slot #706 
- [ ] Implement beaconchain_peers metric #705

**Comment by jrhea** [comment]
@ajsutton what's the status on this? Are #705 through #708 still open?

**Comment by ajsutton** [comment]
I think they're all still open actually.  We've got most of the metrics from one issue but not all, and I suspect the numbers aren't right in a couple of cases.  Basically, the framework is good, the actual metrics not so much right now.

**Comment by ajsutton** [comment]
Going to close this one as the framework is in place. The other tickets can track the work to be done on specific metrics.
