### ISSUE TITLE
Devnet 6 changes

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#7249]
https://github.com/ethereum/consensus-specs/releases/tag/v1.4.0-alpha.2

- [x] Update MAX_BLOBS_PER_BLOCK to 6 and add Deneb networking configs to yaml files https://github.com/ethereum/consensus-specs/pull/3410
- [x] Remove assert from is_data_available https://github.com/ethereum/consensus-specs/pull/3404
- [x] De-duplicate range references in BlobSidecarsByRange https://github.com/ethereum/consensus-specs/pull/3162
- [x] specially mark EIP4844 changes https://github.com/ethereum/consensus-specs/pull/3406
