### ISSUE TITLE
VC failover switch back to primary node when target peer count is met

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#7356]
Inspired from a discussion on Discord: https://discord.com/channels/697535391594446898/697539289042649190/1128622402822213692

After a primary BN is recovering from network outage/restart, it would be good to be able to configure VC to switch back to primary only when certain amount of peers is met. This will allow for a smoother failover. A standard beacon api endpoint could be used to get the peer count: https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Node/getPeerCount

Tasks:
- [x] #8413 Add getPeerCount to the validator api channel
- [x] #8414 Add the getPeerCount remote validator api channel handler
- [x] #8415 Use the new `getPeerCount` in the BN fallback logic
