### ISSUE TITLE
Move to sidecar inclusion proof

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#7654]
Issue to track, high level, the implementation status for https://github.com/ethereum/consensus-specs/pull/3531 and related spec changes

- [x] Migrate data structures
- [x] Add configuration params
- [x] Add inclusion proof creation and validation
- [x] Update gossip rules
- [x] Update RPC methods (by root \ by range)
- [x] Update block import (in-sync, forward sync, historical sync)
- [x] Update storage 
- [x] Update block production flow
- [x] Update builder block production flow https://github.com/ethereum/builder-specs/pull/90
- [x] Update block production API (remote VC) https://github.com/Consensys/teku/issues/7651
- [x] Update beacon API (get blobs)
- [x] Check that we always validate number of commitments/blobs (shouldn't exceed maxBlobs) when it comes from external source
- [x] Optimize `BlobSidecarGossipValidator` by checking `blockHeader` signature (and maybe some other fields if possible) only once for BlobSidecars from one block
- [x] Re-enable reference tests (disabled here: #7695)
- [x] Cleanup (no more traces of previous implementation)
