### ISSUE TITLE
[EIP-6110] Supply validator deposits on chain

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#7898]
### Description
Provides validator deposits as a list of deposit operations added to the Execution Layer block

- [x] Add the necessary config
- [x] Add new container `DepositReceipt`
- [x] Extend `ExecutionPayload`  with `deposit_receipts`
- [x] Extend `ExecutionPayloadHeader` with `deposit_receipts_root`
- [x] Append BeaconState with `deposit_receipts_start_index`
- [x] Modify `ElectraStateUpgrade` to set the new field to `UNSET_DEPOSIT_RECEIPTS_START_INDEX`
- [x] Create/Modify `getPayloadV4` and `newPayloadV4` using the new ExecutionPayload
- [x] Modify `get_eth1_deposit_count` during block proposal
- [x] Modify block processing when state transitioning https://github.com/ethereum/consensus-specs/blob/dev/specs/_features/eip6110/beacon-chain.md#block-processing
- [x] Stop `Eth1Data` polling/voting when `state.eth1_deposit_index == state.deposit_receipts_start_index`
- [x] Make `ValidatorIndexCache` re-org resistant

### References
- https://eips.ethereum.org/EIPS/eip-6110
- https://github.com/ethereum/consensus-specs/tree/dev/specs/_features/eip6110
- https://www.youtube.com/watch?v=tRTBgCN9VgY
