### ISSUE TITLE
[EIP-7549] Move committee index outside attestation

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#7965]
### Description
Move the committee index field outside of the signed Attestation message to allow aggregation of equal consensus votes.

### References
- [EIP-7549](https://eips.ethereum.org/EIPS/eip-7549)
- [Consensus Spec PR](https://github.com/ethereum/consensus-specs/pull/3559)
- [Updated Consensus Spec](https://github.com/ethereum/consensus-specs/tree/dev/specs/_features/eip7549)

### Tasks
- [x] #8089 Refactor get_attesting_indices
- [x] #8026 Add/update attestations containers 
- [x] #8123 Add/update index attestations containers 
- [x] #8031 Update the attestation processing
- [x] #8156 Flattern aggregation bits
- [x] #8103 Update preset values
- [x] #8130 Update beacon block body

Once the previous done, we can start merging the changes in master while progressing on the following:

- [x] #8101 Update attestation production
- [x] #8027 Update attestation aggregation logic
~~#8270 Replace `committee_bits` with `committee_indices`~~
- [x] #8099 Update the aggregation gossip topic
- [x] #8100 Update the attestation gossip topic
- [x] #8340 Move `committee_bits` property to the end
- [x] #8029 Add the `GetAttestations` v2 APIs (attestations pool)
- [x] #8424 Add the `PostAttestation` v2 APIs (attestations pool)
- [x] #8264 Add the `GetBlockAttestations` v2 APIs (block's attestations)
- [x] #8122 Add the `GetAttesterSlashings` v2 API (get attester slashing)
- [x] #8425 Add the `PostAttesterSlashing` v2 API (post attester slashing)
- [x] #8420 Add the `GetAggregateAttestation` v2 API
- [x] #8439 Add the `PostAggregateAttestation` v2 API

### Tech debt:
- [x] ELECTRA milestone over `AggregateAttestationValidatorTest` and implement `ElectraAttestationValidatorTest`

### Possible evolutions
- [x] #8554 Separate type for on-chain attestation aggregates
- [x] #8555 Separate type for unaggregated network attestations
