### ISSUE TITLE
Interop Lock-in TODO

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#836]
#### Highest Priority
- [x] Finish update to 0.8.x and merge to master
- [x] All reference tests passing
- [x] Implement a HELLO message so we can perform the basic handshake.
- [x] Test Mothra' static peering mechanism
- [x] Validator Client updates
- [x]  Attestations: must be able to processes aggregated attestations
