### ISSUE TITLE
Allow the option to store blobs to filesystem as they're being removed from database

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#8513]
Blobs are currently stored for the mandatory time in database and then deleted.

Rather than simply deleting them, it'd be helpful to be able to write the blobs to filesystem.

I could imagine keeping this relatively simple and just specifying something like `--data-storage-store-old-blobs-path=/data` and we'd then start writing all blobs to the filesystem before they get archived.

Theres a tool already in use https://github.com/base-org/blob-archiver that basically dumps the blobs api output per block, we could do similar re. file naming etc potentially if its not too crazy.. Remembering there'll be 7200 slots per day so we probably want output in some kind of structure.

Work is split into following tasks:
- [x] #8640 adds the concept of a DatabaseArchiveWriter functional interface. This provides the interface to have BlobSidecars written to an seperate archive when pruned.
- [x] #8674 Create a DataArchive interface that has a file system based implementation (e.g. FileSystemDataArchive) to allow writing to BlobSidecars out.
- [x] #8674 Create the configuration option to a DatabaseArchiveWriter implementation to write to the FileSystemDataArchive.
- [x] Add read functionality to the DataArchive interface and allow the ability to return the selected BlobSidecar by slot.
- [ ] Update the Beacon-api /blob_sidecars/{block_id} to allow searching both the database and DataArchive if available.

**Comment by david-ry4n** [comment]
Moved plan to main description.

**Comment by tbenr** [comment]
The plan makes sense to me! bare in mind that you used `fixes xxx` in the first PR description, so once you merge that it will automatically close this one, which instead seems like an "epic" tracking several steps.
I'd move the checkboxes in the main issue description so we can keep it open and track the status.
