### ISSUE TITLE
Failing Reference Tests

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#860]
The following reference tests need to be repaired to begin interoperability testing with other clients:

## Broken tests:

- [ ] ssz_generic tests need to be implemented

- [x] sanity -> blocks (super broken)

  - [x] needs BLS points don't match because it is not a valid key

  - [x] not processing empty slots (fixed in #883)

  - [x] NullPointer exception in `sanitySkippedSlotsSetup` and `sanityVoluntaryExitSetup` (fixed in #883)

  - [x] Only `mainnet` tests implemented, not `minimal` (fixed in #883)

- [x] sanity -> slots (super broken)

  - [x] needs BLS points don't match because it is not a valid key

  - [x] Only `mainnet` tests implemented, not `minimal` (fixed in #883)

  - [x] Incorrectly interpreting input data (starting slot/number of slots) (fixed by #886)

- [x] shuffle setup method `sanityProcessSlot` needs to be renamed, and test label (in _shuffle/shuffling.java_) (fixed in #883)

  - [x] Add `minimal` config (fixed in #883)

- [x] ssz_static (super broken)

- [x] genesis -> validity (super broken)

- [x] one last pass for minimal configurations

## Failing tests

Failing reference tests:

- [x] sanity -> blocks - 2 x 3 failing for each of minimal and mainnet: attestation, historical_batch, voluntary_exit (fixed by #885)

- [x]  sanity -> slots - 1 x 2 failing for each of minimal and mainnet: double_empty_epoch (fixed by #885)

- [x] operations -> deposit: 4 failing - this is temporary, due to commenting out `is_valid_merkle_branch()` in `process_deposit()`

**Comment by dangerousfood** [comment]
I am working `genesis -> validity`

**Comment by benjaminion** [comment]
I'm on the BLS issues with sanity/*
