### ISSUE TITLE
[EIP-6110] Queue deposit requests and apply them during epoch processing

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#8618]
Reference: https://github.com/ethereum/consensus-specs/pull/3818

Tasks:
- [x] Created PendingDeposit container
- [x] Updated presets
- [x] Epoch Processing: remove `process_pending_balance_deposits` / Add `apply_pending_deposit ` and `process_pending_deposit `
- [x] Block Processing: `process_deposit` and related changes (`get_validator_from_deposit`, `add_validator_to_registry`)
- [x] Remove `PendingPartialDeposit` containers
