### ISSUE TITLE
Pectra Devnet 5

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#8738]
Devnet 5 specs: https://notes.ethereum.org/@ethpandaops/pectra-devnet-5

Target reference tests version: `v1.5.0-alpha.9` (https://github.com/ethereum/consensus-specs/pull/3982)

- [x] https://github.com/Consensys/teku/issues/8743
  - [x] https://github.com/Consensys/teku/issues/8767
- [x] https://github.com/Consensys/teku/issues/8801
- [x] https://github.com/Consensys/teku/issues/8804

**Comment by tbenr** [comment]
this https://github.com/Consensys/teku/issues/8743 is probably targeted for devnet5

**Comment by tbenr** [comment]
maybe this https://github.com/Consensys/teku/issues/8767 too?

**Comment by tbenr** [comment]
https://github.com/Consensys/teku/issues/8801

**Comment by tbenr** [comment]
https://github.com/Consensys/teku/issues/8804
